### ISSUE TITLE
Define a CIBA OpenAPI security scheme

### ISSUE THREAD

**Issue by AxelNennker** [camaraproject/IdentityAndConsentManagement#157]
**Problem description**
In Camara guidelines on how an API is described in [OpenAPI](https://www.openapis.org/) are documented in the [Commonalities' API guidelines document](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#11-definition-in-openapi).

Currently there is no guideline on how an API can express that it supports or requires CIBA.

**Possible evolution**

ICM should define a common definition of a CIBA security scheme and propose a guideline for API designers to use that security scheme to Commonalities

Suggestion: 

---

An Camara API using CIBA should use the following security scheme definition.

```yaml
components:
  securitySchemes:
    ciba:
      type: oauth2
      flows:
        x-ciba:
          authorizationUrl: https://az.example.com/bc-authorize
          tokenUrl: https://az.example.com/token
          x-cibaDeliveryModes: ["poll"]
```

The `ciba` flow is going to be defined in [OpenAPI version 3.2](https://github.com/OAI/OpenAPI-Specification/blob/v3.2.0-dev/versions/3.2.0.md#oauth-flows-object). For now Camara is using the in OpenAPI extension mechanism using the `x-` prefix because Camara is using [OpenAPI version 3.0.3](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md).

---

**Additional context**

OpenAPI tools and especially code generators are currently ignoring OpenAPI security. 
E.g. if you specify the openIdConfigurationUrl or not, the generated Java client code does not change.

Specifying security in OpenAPI is valuable information for developers though and should be integrated into Camara OpenAPI files.

OpenAPI is viewing OIDC as an evolution of OAuth2 and API designers can only specify the openIdConfigurationUrl to an security object of type `openIdConnect`. As such CIBA is also an evalution of OAuth2 and OpenAPI is going to define the CIBA flow in the security object of type `oauth2`.
