### ISSUE TITLE
Provide API Design guidelines for OAuth2 client credentials

### ISSUE THREAD

**Issue by AxelNennker** [camaraproject/IdentityAndConsentManagement#171]
**Problem description**
There are Camara APIs that do not involve personal data and by specifying the openid-security-scheme in the API yaml file API consumers are missing important information. If no personal data is processed then an OAuth2 client credentials security scheme is what API consumers should find in the API yaml file. 

There is currently no guideline for API designers how to specify OAuth2 client credentials.

The following are two Camara APIs that do not involve personal data:
https://github.com/camaraproject/PopulationDensityData/blob/main/code/API_definitions/population-density-data.yaml @jgarciahospital 
https://github.com/camaraproject/QualityOnDemand/ especially https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qos-profiles.yaml @jlurien @eric-murray 

**Expected action**
Provide a guideline for API designer on how to specify a security scheme that allows OAuth2 client credentials.

https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qos-profiles.yaml is currently using this security scheme

```
components:
  securitySchemes:
    oAuth2ClientCredentials:
      description: |
        The QoS Profiles API makes use of the OAUTH 2.0 client credentials grant which is applicable for server to server use cases involving trusted partners or clients without any protected user data involved. In this method the API invoker client is registered as a confidential client with an authorization grant type of client_credentials
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.example.com/oauth/token
          scopes: {}
```

**Additional context**

TSC [agreed](https://github.com/camaraproject/Governance/blob/main/documentation/MeetingMinutes/TSC/TSC-2023-10-19-Meeting-Minutes.md#commonalities--icm) on October 19, 2023 :

Update OpenAPI security guideline (https://github.com/camaraproject/Commonalities/pull/57)

    Agreement to use openId connect discovery clause in the Open API Specification (OAS) and provided API scheme for the API in another form (either in seperate file or as documentation section within the OAS).
    Documentation must also list possible security schema for the APIs.
    [Action] Telefonica will propose a wording.
    We need also to check how security schema are managed in 3GPP
    Tanja De Groot provided following links: [3GPP 5G APIs](https://forge.3gpp.org/rep/all/5G_APIs), esp. [TS29122_CommonData.yaml](https://forge.3gpp.org/rep/all/5G_APIs/-/blob/REL-18/TS29122_CommonData.yaml)
    Shilpa added the following specific link: [TS24558_Eees_EASDiscovery.yaml](https://forge.3gpp.org/rep/all/5G_APIs/-/blob/REL-18/TS24558_Eees_EASDiscovery.yaml)
    Voting in Commonalities and ICM groups: as their decisions affect many other working groups, discussions needing a voting should be escalated to TSC.Update OpenAPI security guideline (https://github.com/camaraproject/Commonalities/pull/57)

    Agreement to use openId connect discovery clause in the Open API Specification (OAS) and provided API scheme for the API in another form (either in seperate file or as documentation section within the OAS).
    Documentation must also list possible security schema for the APIs.
    [Action] Telefonica will propose a wording.
    We need also to check how security schema are managed in 3GPP
    Tanja De Groot provided following links: [3GPP 5G APIs](https://forge.3gpp.org/rep/all/5G_APIs), esp. [TS29122_CommonData.yaml](https://forge.3gpp.org/rep/all/5G_APIs/-/blob/REL-18/TS29122_CommonData.yaml)
    Shilpa added the following specific link: [TS24558_Eees_EASDiscovery.yaml](https://forge.3gpp.org/rep/all/5G_APIs/-/blob/REL-18/TS24558_Eees_EASDiscovery.yaml)
    Voting in Commonalities and ICM groups: as their decisions affect many other working groups, discussions needing a voting should be escalated to TSC.

PopulationDensityData was created in December 2023 after the TSC agreement.
[QoS Profiles](https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qos-profiles.yaml) was split from QoS also after the TSC agreement.

I, @AxelNennker, think the TSC agreement should be re-visited because now we have Camara API that are client-credentials only.
There should be a guideline for API Designers in API Design guidelines how to specify oauth2 client-credentials in API yaml files.
API consumers would miss important information in the yaml files if the read the openid-security scheme in the API yaml file, but in fact the API requires client credentials.
